# Generated by Django 2.2.10 on 2023-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
                ('points', models.IntegerField()),
                ('rang', models.IntegerField(default=0)),
            ],
        ),
    ]
