# Generated by Django 2.2.10 on 2023-01-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrocoins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classement',
            name='rang',
            field=models.IntegerField(default=0),
        ),
    ]
