 # Generated by Django 4.1.3 on 2023-01-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('num', models.EmailField(max_length=254)),
                ('couvert', models.BooleanField()),
                ('mess', models.TextField(blank=True)),
                ('vieux', models.BooleanField()),
            ],
        ),
    ]
