# Generated by Django 2.2.10 on 2023-01-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('Mail', models.CharField(max_length=20)),
                ('Objet', models.CharField(max_length=30)),
                ('Message', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
